# Dockerfile to build a jmeter container able to drive acmeair
# Results appear on /output in the container
# Must specify the hostname for the acmeair application (or localhost will be assumed)
#FROM icr.io/appcafe/ibm-semeru-runtimes:open-21-ea-jdk-ubi9
FROM icr.io/appcafe/ibm-semeru-runtimes:open-17-jdk-ubi

ENV JMETER_VERSION 5.5

# Install pre-requisite packages
USER root
RUN yum -y install wget unzip

# Install jmeter 
RUN   mkdir /jmeter \
        && mkdir /output \
        && cd /jmeter/ \
        && wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz \
        && tar -xzf apache-jmeter-$JMETER_VERSION.tgz \ 
        && rm apache-jmeter-$JMETER_VERSION.tgz 

# Set jmeter home, add jmeter to the PATH and set JVM options
ENV JMETER_HOME="/jmeter/apache-jmeter-$JMETER_VERSION"

# Add jmeter to the PATH
ENV PATH="$JMETER_HOME/bin:$PATH"

# Set JVM options
ENV JVM_ARGS "-Xtune:virtualized -Xshareclasses:none -Xms1g -Xmx1g"

# We should set summariser.interval=6 in bin/jmeter.properties
RUN echo 'summariser.interval=6' >> $JMETER_HOME/bin/jmeter.properties
RUN echo 'CookieManager.save.cookies=true' >> $JMETER_HOME/bin/jmeter.properties


# Copy the script to be executed and other needed files
COPY DriverFiles/AcmeAir-v5.jmx $JMETER_HOME/AcmeAir-v5.jmx
COPY DriverFiles/Airports.csv $JMETER_HOME/Airports.csv
COPY DriverFiles/Airports2.csv $JMETER_HOME/Airports2.csv
COPY DriverFiles/hosts.csv $JMETER_HOME/hosts.csv
COPY DriverFiles/json-simple-1.1.1.jar $JMETER_HOME/lib/ext/
COPY DriverFiles/jmeter-plugins-influxdb2-listener-2.2.jar $JMETER_HOME/lib/ext/
COPY DriverFiles/acmeair-jmeter-2.0.0-SNAPSHOT.jar $JMETER_HOME/lib/ext/
COPY DriverFiles/applyLoad.sh $JMETER_HOME/bin/applyLoad.sh
RUN chmod u+x $JMETER_HOME/bin/applyLoad.sh

# Environment variables that we want the user to redefine
ENV JPORT=9080 
ENV JUSERBOTTOM=0
ENV JUSER=199
ENV JURL=/
ENV JTHREAD=15
ENV JDURATION=60
ENV JRAMP=0
ENV JHOST=localhost
ENV JTHINKTIME=0
ENV JINFLUXDBBUCKET=jmeter
ENV JINFLUXDBADDR=localhost

ENTRYPOINT ["applyLoad.sh"]


