apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: acmeair-sccio
  namespace: scclab-rh10
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: acmeair-sccio
      annotations:
        autoscaling.knative.dev/class: "hpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "cpu"
        autoscaling.knative.dev/target: "50"
        # This is what we say that a single pod should be able to handle.
        #autoscaling.knative.dev/target: "100"
        # Agregate the metrics over 30 seconds
        #autoscaling.knative.dev/window: "30s"
        # wait 120 seconds at reduced concurrency before a scale-down decision is applied.
        autoscaling.knative.dev/scale-down-delay: "10s"
        # Scale up to 2 pods
        autoscaling.knative.dev/max-scale: "15"
    spec:
      serviceAccountName: instanton-sa-scclab-rh10
      nodeSelector:
        demotag: worker3
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/scclab-rh10/liberty-acmeair-ee8:24.0.0.4-instanton
        imagePullPolicy: Always
        name: acmeair-sccio
        env:
        - name: JVM_ARGS
          value: "-XX:+UseJITServer -XX:JITServerAddress=jitserver2 -XX:JITServerPort=38401"
        - name: OPENJ9_RESTORE_JAVA_OPTIONS
          value: "-XX:+UseJITServer -XX:JITServerAddress=jitserver2 -XX:JITServerPort=38401"
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DBNAME
          value: "acmeair"
        ports:
        - containerPort: 9080
        resources:
          requests:
            memory: "200Mi"
            cpu: "1000m"
          limits:
            memory: "200Mi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 1
          periodSeconds: 1
          failureThreshold: 10
        securityContext:
          allowPrivilegeEscalation: true
          runAsNonRoot: true
          capabilities:
            add:
              - SETPCAP
              - CHECKPOINT_RESTORE
            drop:
              - ALL


