apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: registry-storage
parameters:
  type: gp2
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
